import{a as g,S as b,i as L}from"./assets/vendor-u8rapaCG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const w="46065399-355f71206950d55166b7078e9",S="https://pixabay.com/api/";async function v(t,o=1,n=15){const r=`${S}?key=${w}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{return(await g.get(r)).data}catch(e){throw console.error("Error fetching images:",e),e}}let d;function $(t){const o=document.querySelector(".gallery"),n=t.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}" target="_blank">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",n),d?d.refresh():d=new b(".gallery a")}function a(t){L.error({title:"Error",message:t})}const m=document.querySelector(".search-form"),q=m.querySelector('input[name="searchQuery"]'),E=document.querySelector(".gallery"),y=document.getElementById("loader"),f=document.querySelector(".load-more");let c=1;const u=15;let i="";function P(){y.classList.remove("hidden")}function h(){y.classList.add("hidden")}m.addEventListener("submit",I);f.addEventListener("click",M);async function I(t){if(t.preventDefault(),i=q.value.trim(),E.innerHTML="",c=1,i===""){a("Please enter a search query.");return}await p(i,c)}async function M(){c++,await p(i,c)}async function p(t,o){try{P(),f.classList.add("hidden");const n=await v(t,o,u);if(h(),n.hits.length===0&&o===1){a("Sorry, there are no images matching your search query. Please try again!");return}$(n.hits),n.hits.length<u||n.totalHits<=o*u?a("We're sorry, but you've reached the end of search results."):f.classList.remove("hidden"),O()}catch{h(),a("Something went wrong. Please try again later.")}}function O(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
