import{a as g,S as b,i as L}from"./assets/vendor-u8rapaCG.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const w="46065399-355f71206950d55166b7078e9",S="https://pixabay.com/api/";async function v(t,n=1,r=15){const o=`${S}?key=${w}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${r}`;try{return(await g.get(o)).data}catch(e){throw console.error("Error fetching images:",e),e}}let u;function $(t){const n=document.querySelector(".gallery"),r=t.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}" target="_blank">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </li>
    `).join("");n.insertAdjacentHTML("beforeend",r),u?u.refresh():u=new b(".gallery a")}function a(t){L.error({title:"Error",message:t})}const m=document.querySelector(".search-form"),E=m.querySelector('input[name="searchQuery"]'),q=document.querySelector(".gallery"),p=document.getElementById("loader"),i=document.createElement("button");i.textContent="Load more";i.classList.add("btn","load-more");document.body.appendChild(i);i.style.display="none";let c=1;const f=15;let l="";function P(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}m.addEventListener("submit",I);i.addEventListener("click",C);function I(t){if(t.preventDefault(),l=E.value.trim(),q.innerHTML="",c=1,l===""){a("Please enter a search query.");return}y(l,c)}function C(){c++,y(l,c)}function y(t,n){P(),i.style.display="none",v(t,n,f).then(r=>{if(h(),r.hits.length===0&&n===1){a("Sorry, there are no images matching your search query. Please try again!");return}$(r.hits),r.hits.length<f||r.totalHits<=n*f?a("We're sorry, but you've reached the end of search results."):i.style.display="block",M()}).catch(r=>{h(),a("Something went wrong. Please try again later."),console.log(r)})}function M(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
